### ISSUE TITLE
Not Enough Content

### ISSUE THREAD

**Issue by ZacharyP27** [vanssx3/passwordCracker#2]
I've already used all the ciphers what now??? This is why this program needs a paid DLC, there isn't enough content in this program to last someone more than 1 hour unless you are just doing the same stuff over and over again. Paid DLC should include more hashes and different password cracking attacks. Plz add.

**Comment by vanssx3** [comment]
hold up bruh passma is coming, its gonna be free dlc so you can make your own passwords to crack and they WILL take more than an hour to crack
ty for the feedback 😁👍
